### PR TITLE
Advanced binarynet tutorial

### PR DESCRIPTION
**Pull request by jamescook106**

### CODE REVIEW

**Comment by jamescook106** [comment]
@lgeiger updated in latest commit

**Comment by lgeiger** [comment]
@jamescook106 it looks like you commited unrelated changes in the simple binarynet example by accident

**Comment by jamescook106** [comment]
I committed the removal of the activation function, and reprinted the model.summary. Will check tomorrow if I have done something in addition

**Comment by lgeiger** [comment]
> I committed the removal of the activation function, and reprinted the model.summary. Will check tomorrow if I have done something in addition

Sorry, looks like GitHub just had some problems rendering the preview for me. Looks good 👍

**Pull request merged**
