### PR TITLE
Lazily compute quantized_weights

### PR DESCRIPTION
**Pull request by lgeiger**
We are running into strange GPU OOM errors.

@jamescook106 Could you test if this worksaround the TensorFlow issue?

In the future I'd be in favor of removing the `quantized_weights` and `quantized_latent_weights` properties. This PR only makes them lazily computed in order to not break the summary and xavier rescaling.

### CODE REVIEW

**Comment by jamescook106** [comment]
Testing as we speak. Note the hasattr(l, "quantized_weights") syntax still works

**Comment by jamescook106** [comment]
This does not fix the bug

**Comment by jamescook106** [comment]
Screenshot from 2019-05-29 10-31-20

**Comment by lgeiger** [comment]
It looks like your memory error is unrelated. I still think this PR is valuable. I will go ahead and merge it.

**Pull request merged**
